# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f7e1e37eef8cd18018028ca77d2421679950c285652d0a73022e1380921a0ddee6221f2b09e51e5092dc2a72f7bb3ac9179c476077a67fa1b8def796815d813

test:
  secret_key_base: db538ab784105db2be2cbb276427c3e330a243587a3ce300816b10679033c23f7c9d602bf82f88e9da29843721c493b571a1820a7027510d674ad5fee1bc0891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
